routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', "ClientController@index");

Route::group(["middleware" => "auth"], function() {
    // category
    Route::resource("/category", "CategoryController", ["except" => ["show"]]);
    Route::resource("/tag", "TagController", ["except" => ["show"]]);

    // post
    Route::get("/post/trashed", "PostController@showTrashedPosts")->name("post.trashed");
    Route::get("/post/trashed/{post}", "PostController@restoreTrashedPosts")->name("post.trashed.restore");
    Route::delete("/post/trashed/{post}", "PostController@deleteTrashedPost")->name("post.trashed.destroy");
    Route::resource("/post", "PostController");

    // user
    Route::resource("/user", "UserController");

    // home
    Route::get("/home", "HomeController@index")->name("home");
});

Route::fallback(function () {
    return view("pages.not-found");
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{

    use SoftDeletes;

    protected $fillable = ["title", "category_id", "title", "content", "image", "slug", "user_id"];

    public function category() {
        return $this->belongsTo("App\Models\Category");
    }

    public function tags() {
        return $this->belongsToMany("App\Models\Tag");
    }

    public function user() {
        return $this->belongsTo("App\User");
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Models\Category;
use App\Models\Tag;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::latest()->paginate(5);
        $title = "Posts";

        return view("admin.post.index", compact("posts", "title"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();
        $title = "Create New Post";

        return view("admin.post.create", compact("categories", "tags", "title"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            "title" => "required|max:255",
            "category_id" => "required",
            "content" => "required",
            "image" => "required"
        ]);

        $image = $request->image;
        $imageNewName = uniqid() . "_" . $image->getClientOriginalName();

        $post = Post::create([
            "title" => $request->title,
            "category_id" => $request->category_id,
            "content" => $request->content,
            "image" => "uploads/posts/" . $imageNewName,
            "slug" => Str::slug($request->title),
            "user_id" => Auth::id()
        ]);

        $post->tags()->attach($request->tags);

        $image->move(public_path() .  "/uploads/posts/", $imageNewName);

        return redirect(route("post.index"))->with("success", $post->title . " has been created successfully.");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categories = Category::all();
        $tags = Tag::all();
        $title = "Edit Post";

        return view("admin.post.edit", compact("post", "categories", "tags", "title"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $this->validate($request, [
            "title" => "required|max:255",
            "category_id" => "required",
            "content" => "required"
        ]);

        $updatedPostData = [
            "title" => $request->title,
            "category_id" => $request->category_id,
            "content" => $request->content,
            "slug" => Str::slug($request->title)
        ];

        if ($request->hasFile("image")) {
            $image = $request->image;
            $imageNewName = uniqid() . "_" . $image->getClientOriginalName();
            $image->move("uploads/posts/", $imageNewName);

            $updatedPostData["image"] = "uploads/posts/" . $imageNewName;
        }

        $post->tags()->sync($request->tags);
        $post->update($updatedPostData);

        return redirect(route("post.index"))->with("success", $post->title . " has been updated successfully.");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();
        return redirect(route("post.index"))->with("success", $post->title . " has been moved to trashed posts successfully.");
    }

    public function showTrashedPosts() {
        $posts = Post::onlyTrashed()->paginate(5);
        $title = "Trashed Posts";

        return view("admin.post.trashed_posts", compact("posts", "title"));
    }

    public function restoreTrashedPosts($id) {
        $restoredPost = Post::withTrashed()->where("id", $id)->first();
        $restoredPost->restore();

        return redirect(route("post.index"))->with("success", $restoredPost->title . " has been restored successfully.");
    }

    public function deleteTrashedPost($id) {
        $restoredPost = Post::withTrashed()->where("id", $id)->first();

        $imageName = substr($restoredPost->image, 14);
        $filePath = public_path() . "/uploads/posts/" . $imageName;

        if(File::exists($filePath)) {
            File::delete($filePath);
        }

        $restoredPost->forceDelete();

        return redirect(route("post.index"))->with("success", $restoredPost->title . " has been deleted successfully.");
    }
}

resources/views/admin/post/create.blade.php
@extends('admin.index')

@section('title', $title)

@section('content')
<div class="row">
    <div class="col-12">
        @if ($errors->any())
        <div class="alert alert-danger">
            <p><b>Error</b></p>
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif

        <div class="card">
            <div class="card-header">
                <h4>{{ $title }}</h4>
            </div>

            <div class="card-body">
                <form id="newPostForm" action="{{ route('post.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf

                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Title</label>
                        <div class="col-sm-12 col-md-7">
                            <input name="title" type="text" class="form-control" placeholder="Please enter post title">
                        </div>
                    </div>

                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Category</label>
                        <div class="col-sm-12 col-md-7">
                            <select name="category_id" class="form-control selectric">
                                @foreach ($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Tags</label>
                        <div class="col-sm-12 col-md-7">
                            <select name="tags[]" class="form-control select2" multiple="">
                                @foreach ($tags as $tag)
                                <option value="{{ $tag->id }}">{{ $tag->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Content</label>
                        <div class="col-sm-12 col-md-7">
                            <textarea name="content" class="form-control"
                                placeholder="Please enter post content"></textarea>
                        </div>
                    </div>

                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Image</label>
                        <div class="col-sm-12 col-md-7">
                            <input type="file" type="image" name="image" id="image">
                        </div>
                    </div>

                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                        <div class="col-sm-12 col-md-7">
                            <button onclick="submitPost()" class="btn btn-primary">Submit</button>
                        </div>
                    </div>

                    <script>
                        function submitPost() {
                            document.getElementById("newPostForm").submit();
                        }
                    </script>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/post/edit.blade.php
@extends('admin.index')

@section('title', $title)

@section('content')
<div class="row">
    <div class="col-12">
        @if ($errors->any())
        <div class="alert alert-danger">
            <p><b>Error</b></p>
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif

        <div class="card">
            <div class="card-header">
                <h4>{{ $title }}</h4>
            </div>

            <div class="card-body">
                <form id="editPostForm" action="{{ route('post.update', $post) }}" method="POST"
                    enctype="multipart/form-data">
                    @csrf
                    @method("PUT")

                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Title</label>
                        <div class="col-sm-12 col-md-7">
                            <input value="{{ $post->title }}" name="title" type="text" class="form-control"
                                placeholder="Please enter post title">
                        </div>
                    </div>

                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Category</label>
                        <div class="col-sm-12 col-md-7">
                            <select name="category_id" class="form-control selectric">
                                @foreach ($categories as $category)
                                <option value="{{ $category->id }}" @if ($post->category_id == $category->id)
                                    selected
                                    @endif
                                    >{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Tags</label>
                        <div class="col-sm-12 col-md-7">
                            <select name="tags[]" class="form-control select2" multiple="">
                                @foreach ($tags as $tag)
                                <option value="{{ $tag->id }}" @foreach ($post->tags as $selectedTag)
                                    @if ($selectedTag->id == $tag->id)
                                    selected
                                    @endif
                                    @endforeach
                                    >{{ $tag->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Content</label>
                        <div class="col-sm-12 col-md-7">
                            <textarea name="content" class="form-control"
                                placeholder="Please enter post content">{{ $post->content }}</textarea>
                        </div>
                    </div>

                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Thumbnail</label>
                        <div class="col-sm-12 col-md-7">
                            <img src="{{ asset($post->image) }}" alt="{{ $post->title }}" class="img-thumbnail"
                                style="height: 200px;">
                        </div>
                    </div>


                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Image</label>
                        <div class="col-sm-12 col-md-7">
                            <input value="{{ $post->image }}" type="file" type="image" name="image" id="image">
                        </div>
                    </div>

                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                        <div class="col-sm-12 col-md-7">
                            <button onclick="submitPost()" class="btn btn-primary">Submit</button>
                        </div>
                    </div>

                    <script>
                        function submitPost() {
                            document.getElementById("editPostForm").submit();
                        }
                    </script>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/post/index.blade.php
@extends('admin.index')

@section('title', $title)

@section('content')

<div class="col-12">
    <div class="card">
        @include('admin.partials.alerts')

        <div class="card-header">
            <h4>{{ $title }}</h4>

            <div class="card-header-action">
                <a href="{{ route('post.create') }}" class="btn btn-success">Create</a>
            </div>
        </div>

        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-striped table-md">
                    <tr>
                        <th>No.</th>
                        <th>Author</th>
                        <th>Title</th>
                        <th>Category</th>
                        <th>Tags</th>
                        <th>Image</th>
                        <th>Action</th>
                    </tr>

                    @foreach ($posts as $post)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $post->user->name }}</td>
                        <td>{{ $post->title }}</td>
                        <td>{{ $post->category->name }}</td>
                        <td>
                            @foreach ($post->tags as $tag)
                            <div class="badge badge-pill badge-primary mb-1">{{ $tag->name }}</div>
                            @endforeach
                        </td>
                        <td>
                            <img src="{{ asset($post->image) }}" alt="{{ $post->title }}" class="img-thumbnail"
                                style="height: 100px;">
                        </td>
                        <td>
                            <form action="{{ route('post.destroy', $post) }}" method="POST">
                                @csrf
                                @method("DELETE")

                                <a href="{{ route('post.edit', $post) }}" class="btn btn-sm btn-primary">Edit</a>

                                <button type="submit" class="btn btn-sm btn-warning">Delete</button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </table>
            </div>
        </div>

        <div class="card-footer text-right">
            <nav class="d-inline-block">
                {{ $posts->links()}}
            </nav>
        </div>
    </div>
</div>

@endsection

resources/views/admin/post/trashed_posts.blade.php
@extends('admin.index')

@section('title', $title)

@section('content')

<div class="col-12">
    <div class="card">
        @include('admin.partials.alerts')

        <div class="card-header">
            <h4>{{ $title }}</h4>
        </div>

        <div class="card-body">
            @if (count($posts))
            <div class="table-responsive">
                <table class="table table-striped table-md">
                    <tr>
                        <th>No.</th>
                        <th>Title</th>
                        <th>Category</th>
                        <th>Tags</th>
                        <th>Image</th>
                        <th>Action</th>
                    </tr>

                    @foreach ($posts as $post)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $post->title }}</td>
                        <td>{{ $post->category->name }}</td>
                        <td>
                            @foreach ($post->tags as $tag)
                            <div class="badge badge-pill badge-primary mb-1">{{ $tag->name }}</div>
                            @endforeach
                        </td>
                        <td>
                            <img src="{{ asset($post->image) }}" alt="{{ $post->title }}" class="img-thumbnail"
                                style="height: 100px;">
                        </td>
                        <td>
                            <form action="{{ route('post.trashed.destroy', $post->id) }}" method="POST">
                                @csrf
                                @method("DELETE")

                                <a href="{{ route('post.trashed.restore', $post->id) }}"
                                    class="btn btn-sm btn-primary">Restore</a>

                                <button type="submit" class="btn btn-sm btn-warning">Delete</button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </table>
            </div>
            @else
            <div class="buttons">
                <p>There are no trashed posts yet.</p>
            </div>
            @endif
        </div>

        <div class="card-footer text-right">
            <nav class="d-inline-block">
                {{ $posts->links()}}
            </nav>
        </div>
    </div>
</div>

@endsection