routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', "ClientController@index");

Route::group(["middleware" => "auth"], function() {
    // category
    Route::resource("/category", "CategoryController", ["except" => ["show"]]);
    Route::resource("/tag", "TagController", ["except" => ["show"]]);

    // post
    Route::get("/post/trashed", "PostController@showTrashedPosts")->name("post.trashed");
    Route::get("/post/trashed/{post}", "PostController@restoreTrashedPosts")->name("post.trashed.restore");
    Route::delete("/post/trashed/{post}", "PostController@deleteTrashedPost")->name("post.trashed.destroy");
    Route::resource("/post", "PostController");

    // user
    Route::resource("/user", "UserController");

    // home
    Route::get("/home", "HomeController@index")->name("home");
});

Route::fallback(function () {
    return view("pages.not-found");
});

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = ["name", "slug"];

    public function posts() {
        return $this->belongsToMany("App\Models\Post");
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::latest()->paginate(5);
        $title = "Tag List";

        return view("admin.tag.index", compact("tags", "title"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $title = "Create New Tag";

        return view("admin.tag.create", compact("title"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            "name" => "required|max:20"
        ]);

        $tag = Tag::create([
            "name" => $request->name,
            "slug" => Str::slug($request->name)
        ]);

        return redirect(route("tag.index"))->with("success", $tag->name . " has been created successfully.");
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        $title = "Edit Tag";
        return view("admin.tag.edit", compact("tag", "title"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tag $tag)
    {
        $this->validate($request, [
            "name" => "required|max:20"
        ]);

        $tag->update([
            "name" => $request->name,
            "slug" => Str::slug($request->name)
        ]);

        return redirect(route("tag.index"))->with("success", $tag->name . " has been updated successfully.");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        $tag->delete();
        return redirect(route("tag.index"))->with("success", $tag->name . " has been deleted successfully.");
    }
}

resources/views/admin/tag/create.blade.php
@extends('admin.index')

@section('title', $title)

@section('content')
<div class="row">
    <div class="col-12">
        @if ($errors->any())
        <div class="alert alert-danger">
            <p><b>Error</b></p>
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif

        <div class="card">
            <div class="card-header">
                <h4>{{ $title }}</h4>
            </div>

            <div class="card-body">
                <form action="{{ route('tag.store') }}" method="POST">
                    @csrf

                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" name="name" class="form-control" placeholder="Please enter tag name">
                    </div>

                    <button class="btn btn-primary float-right">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/tag/edit.blade.php
@extends('admin.index')

@section('title', $title)

@section('content')
<div class="row">
    <div class="col-12">
        @if ($errors->any())
        <div class="alert alert-danger">
            <p><b>Error</b></p>
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif

        <div class="card">
            <div class="card-header">
                <h4>{{ $title }}</h4>
            </div>

            <div class="card-body">
                <form action="{{ route('tag.update', $tag) }}" method="POST">
                    @csrf
                    @method("PUT")

                    <div class="form-group">
                        <label>Name</label>
                        <input value="{{ $tag->name }}" type="text" name="name" class="form-control">
                    </div>

                    <button class="btn btn-primary float-right">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/tag/index.blade.php
@extends('admin.index')

@section('title', $title)

@section('content')

<div class="col-12">
    <div class="card">
        @include('admin.partials.alerts')

        <div class="card-header">
            <h4>{{ $title }}</h4>

            <div class="card-header-action">
                <a href="{{ route('tag.create') }}" class="btn btn-success">Create</a>
            </div>
        </div>

        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-striped table-md">
                    <tr>
                        <th>No.</th>
                        <th>Name</th>
                        <th>Created At</th>
                        <th>Updated At</th>
                        <th>Action</th>
                    </tr>

                    @foreach ($tags as $tag)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $tag->name }}</td>
                        <td>{{ $tag->created_at }}</td>
                        <td>{{ $tag->updated_at }}</td>
                        <td>
                            <form action="{{ route('tag.destroy', $tag) }}" method="POST">
                                @csrf
                                @method("DELETE")

                                <a href="{{ route('tag.edit', $tag) }}" class="btn btn-sm btn-primary">Edit</a>

                                <button type="submit" class="btn btn-sm btn-warning">Delete</button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </table>
            </div>
        </div>

        <div class="card-footer text-right">
            <nav class="d-inline-block">
                {{ $tags->links()}}
            </nav>
        </div>
    </div>
</div>

@endsection