routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', "ClientController@index");

Route::group(["middleware" => "auth"], function() {
    // category
    Route::resource("/category", "CategoryController", ["except" => ["show"]]);
    Route::resource("/tag", "TagController", ["except" => ["show"]]);

    // post
    Route::get("/post/trashed", "PostController@showTrashedPosts")->name("post.trashed");
    Route::get("/post/trashed/{post}", "PostController@restoreTrashedPosts")->name("post.trashed.restore");
    Route::delete("/post/trashed/{post}", "PostController@deleteTrashedPost")->name("post.trashed.destroy");
    Route::resource("/post", "PostController");

    // user
    Route::resource("/user", "UserController");

    // home
    Route::get("/home", "HomeController@index")->name("home");
});

Route::fallback(function () {
    return view("pages.not-found");
});

resources/views/admin/partials/alerts.blade.php
@if (session("success"))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ session("success") }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
@endif

resources/views/admin/partials/footer.blade.php
<footer class="main-footer">
    <div class="footer-left">
        Copyright &copy; 2018 <div class="bullet"></div> Design By <a href="https://nauval.in/">Muhamad
            Nauval Azhar</a>
    </div>
    <div class="footer-right">

    </div>
</footer>

resources/views/admin/partials/navbar.blade.php
<div class="navbar-bg"></div>

<nav class="navbar navbar-expand-lg main-navbar">
    <form class="form-inline mr-auto">
        <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
        </ul>
    </form>

    <ul class="navbar-nav navbar-right">
        <li class="dropdown"><a href="#" data-toggle="dropdown"
                class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                <img alt="image" src="{{ asset('admin/dist/assets/img/avatar/avatar-1.png') }}"
                    class="rounded-circle mr-1">
                <div class="d-sm-none d-lg-inline-block">Hi, {{ Auth::user()->name }}</div>
            </a>

            <div class="dropdown-menu dropdown-menu-right">
                <div class="dropdown-title">Logged in 5 min ago</div>
                <a href="features-profile.html" class="dropdown-item has-icon">
                    <i class="far fa-user"></i> Profile
                </a>
                <a href="features-activities.html" class="dropdown-item has-icon">
                    <i class="fas fa-bolt"></i> Activities
                </a>
                <a href="features-settings.html" class="dropdown-item has-icon">
                    <i class="fas fa-cog"></i> Settings
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item has-icon text-danger" href="{{ route('logout') }}" onclick="event.preventDefault();
                document.getElementById('logout-form').submit();">
                    <i class="fas fa-sign-out-alt"></i> Logout
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</nav>

resources/views/admin/partials/sidebar.blade.php
<div class="main-sidebar sidebar-style-2">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
            <a href="index.html">Stisla</a>
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            <a href="index.html">St</a>
        </div>
        <ul class="sidebar-menu">
            <li class="menu-header">Dashboard</li>
            <li class="dropdown">
                <a href="{{ route('home') }}" class="nav-link"><i class="fas fa-fire"></i><span>Dashboard</span></a>
            </li>

            <li class="menu-header">Starter</li>

            <li class="dropdown">
                <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-user"></i>
                    <span>User</span></a>

                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{ route('user.index') }}">User List</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-book-open"></i>
                    <span>Post</span></a>

                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{ route('post.index') }}">Post List</a></li>
                    <li><a class="nav-link" href="{{ route('post.trashed') }}">Trashed Posts</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="far fa-clipboard"></i>
                    <span>Category</span></a>

                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{ route('category.index') }}">Category List</a></li>
                    <li><a class="nav-link" href="{{ route('category.create') }}">Create New Category</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="far fa-bookmark"></i>
                    <span>Tag</span></a>

                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{ route('tag.index') }}">Tag List</a></li>
                    <li><a class="nav-link" href="{{ route('tag.create') }}">Create New Tag</a></li>
                </ul>
            </li>
    </aside>
</div>